title: Role Playing Games
description: Combined site of RPGs I help hosting website information
titles_from_headings:
    enabled: false
defaults:
    -
        scope:
            path: DungeonsAndDragons/4e/ZodiacWheel
        values:
            rpgtitle: Zodiac Wheel
            rpgdescription: A D&D4e game about a cycle of little animals
            rpgrootlink: DungeonsAndDragons/4e/ZodiacWheel/
    -
        scope:
            path: DungeonsAndDragons/4e/Resources
        values:
            rpgtitle: D&D4e Resources
            rpgdescription: Various Resources for D&D4e
            rpgrootlink: DungeonsAndDragons/4e/Resources/
    -
        scope:
            path: DungeonsAndDragons/5e/TalesOfAvernus
        values:
            rpgtitle: Tales of Avernus
            rpgdescription: A D&D5e game about going into hell
            rpgrootlink: DungeonsAndDragons/5e/TalesOfAvernus/
