title: Role Playing Games
description: Combined site of RPGs I help hosting website information
titles_from_headings:
    enabled: false
defaults:
    -
        scope:
            path: 13thAge/RulesAndResources
        values:
            rpgtitle: 13th Age Rules and Resources
            rpgdescription: Various Resources for 13th Age
            rpgrootlink: 13thAge/RulesAndResources
    -
        scope:
            path: BandOfBlades/TheRoadToSkydaggerKeep
        values:
            rpgtitle: The Road to Skydagger Keep
            rpgdescription: A Band of Blades Game
            rpgrootlink: BandOfBlades/TheRoadToSkydaggerKeep/
    -
        scope:
            path: DungeonsAndDragons/4e/ZodiacWheel
        values:
            rpgtitle: Zodiac Wheel
            rpgdescription: A D&D4e game about a cycle of little animals
            rpgrootlink: DungeonsAndDragons/4e/ZodiacWheel/
    -
        scope:
            path: DungeonsAndDragons/4e/ZodiacWheel/AdventureLog
        values:
            subtitlesuffix: Adventure Log
            backlink: ./
    -
        scope:
            path: DungeonsAndDragons/4e/RulesAndResources
        values:
            rpgtitle: D&D4e Rules and Resources
            rpgdescription: Various Resources for D&D4e
            rpgrootlink: DungeonsAndDragons/4e/RulesAndResources/
    -
        scope:
            path: DungeonsAndDragons/5e/TalesOfAvernus
        values:
            rpgtitle: Tales of Avernus
            rpgdescription: A D&D5e game about going into hell
            rpgrootlink: DungeonsAndDragons/5e/TalesOfAvernus/
    -
        scope:
            path: DungeonsAndDragons/5e/TalesOfAvernus/AdventureLog
        values:
            subtitlesuffix: Adventure Log
            backlink: ./
    -
        scope:
            path: Lancer/WhiskeyCompany
        values:
            rpgtitle: Whiskey Company
            rpgdescription: A Lancer game following the exploits of Whiskey Company
            rpgrootlink: Lancer/WhiskeyCompany/
    -
        scope:
            path: Lancer/WhiskeyCompany/MissionLog
        values:
            subtitlesuffix: Mission Log
            backlink: ./
    -
        scope:
            path: RighteousBlood/BloodAndHonour
        values:
            rpgtitle: Blood and Honour
            rpgdescription: Righteous Blood Adventures
            rpgrootlink: RighteousBlood/BloodAndHonour/
    -
        scope:
            path: RighteousBlood/RulesAndResources
        values:
            rpgtitle: Righteous Blood Rules and Resources
            rpgdescription: Wuxia Roleplaying Quick Reference
            rpgrootlink: RighteousBlood/RulesAndResources/
    -
        scope:
            path: Shadowrun/5e/LoneStar
        values:
            rpgtitle: Lone Star
            rpgdescription: An anti-narcotics squad
            rpgrootlink: Shadowrun/5e/LoneStar/
    -
        scope:
            path: Shadowrun/5e/ShadowrunUK
        values:
            rpgtitle: Shadowrun UK
            rpgdescription: An SR5e game set in the UK
            rpgrootlink: Shadowrun/5e/ShadowrunUK/
    -
        scope:
            path: Shadowrun/5e/ShadowrunUK/AdventureLog
        values:
            subtitlesuffix: Adventure Log
            backlink: ./
    -
        scope:
            path: Shadowrun/5e/ShadowrunUK/Contacts
        values:
            subtitlesuffix: Contacts
            backlink: ./
    -
        scope:
            path: Shadowrun/5e/RulesAndResources
        values:
            rpgtitle: Shadowrun 5e Rules and Resources
            rpgdescription: Our Summary of SR5e Rules
            rpgrootlink: Shadowrun/5e/RulesAndResources/
