title: Role Playing Games
description: Combined site of RPGs I help hosting website information
titles_from_headings:
    enabled: false
defaults:
    -
        scope:
            path: TalesOfAvernus
        values:
            rpgtitle: Tales of Avernus
            rpgdescription: A D&D5e game about going into hell
            rpgrootlink: TalesOfAvernus/
    -
        scope:
            path: ZodiacWheel
        values:
            rpgtitle: Zodiac Wheel
            rpgdescription: A D&D4e game about a cycle of little animals
            rpgrootlink: ZodiacWheel/
