title: Role Playing Games
description: Combined site of RPGs I help hosting website information
titles_from_headings:
    enabled: false
defaults:
    -
        values:
            layout: default
    -
        scope:
            path: 13thAge/IlmatrasLastHope
        values:
            rpgtitle: Ilmatra’s Last Hope
            rpgdescription: A 13th Age Horror Game
    -
        scope:
            path: 13thAge/RulesAndResources
        values:
            rpgtitle: Rules and Resources
            rpgdescription: Various Resources for 13th Age
    -
        scope:
            path: 13thAge/SideCampaign
        values:
            rpgtitle: Crown of Axis
            rpgdescription: A 13th Age Side Campaign
    -
        scope:
            path: 13thAge/SwordsAgainstOwlbears
        values:
            rpgtitle: Swords Against Owlbears
            rpgdescription: A 13th Age Oneshot
    -
        scope:
            path: BandOfBlades/TheRoadToSkydaggerKeep
        values:
            rpgtitle: The Road to Skydagger Keep
            rpgdescription: A Band of Blades Game
    -
        scope:
            path: DarkHeresy/GacromosHeresy
        values:
            rpgtitle: Gacromos Heresy
            rpgdescription: Hunt the Heretek
    -
        scope:
            path: DarkHeresy/RulesAndResources
        values:
            rpgtitle: Rules and Resources
            rpgdescription: Various Resources for Dark Heresy
    -
        scope:
            path: DungeonsAndDragons/4e/ScalesOfWar
        values:
            rpgtitle: Scales of War
            rpgdescription: A D&D4e Adventure Path
    -
        scope:
            path: DungeonsAndDragons/4e/ZodiacWheel
        values:
            rpgtitle: Zodiac Wheel
            rpgdescription: A D&D4e Game About a Cycle of Little Animals
    -
        scope:
            path: DungeonsAndDragons/4e/RulesAndResources
        values:
            rpgtitle: Rules and Resources
            rpgdescription: Various Resources for D&D4e
    -
        scope:
            path: DungeonsAndDragons/5e/TalesOfAvernus
        values:
            rpgtitle: Tales of Avernus
            rpgdescription: A D&D5e game about going into hell
    -
        scope:
            path: DungeonsAndDragons/5.5e/EscapingAesilwode
        values:
            rpgtitle: Escaping Aesilwode
            rpgdescription: A D&D5e game about running away
    -
        scope:
            path: Generic
        values:
            rpgtitle: Generic
            rpgdescription: Generic resources for RPGs
    -
        scope:
            path: Lancer/OperationSolsticeRain
        values:
            rpgtitle: Operation Solstice Rain
            rpgdescription: A Lancer side game
    -
        scope:
            path: Lancer/WhiskeyCompany
        values:
            rpgtitle: Whiskey Company
            rpgdescription: A Lancer game following the exploits of Whiskey Company
    -
        scope:
            path: LegendOfTheFiveRings/RulesAndResources
        values:
            rpgtitle: Rules and Resources
            rpgdescription: Various Resources for L5R
    -
        scope:
            path: LegendOfTheFiveRings/WayOfTheBushido
        values:
            rpgtitle: Way of the Bushido
            rpgdescription: Five Volunteers are Given a Job
    -
        scope:
            path: RighteousBlood/BloodAndHonour
        values:
            rpgtitle: Blood and Honour
            rpgdescription: Righteous Blood Adventures
    -
        scope:
            path: RighteousBlood/RulesAndResources
        values:
            rpgtitle: Rules and Resources
            rpgdescription: Wuxia Roleplaying Quick Reference
    -
        scope:
            path: RollForShoes/KitchenKhaos
        values:
            rpgtitle: Kitchen Khaos
            rpgdescription: Courtly servants rush to prepare and serve a fantastical feast
    -
        scope:
            path: RollForShoes/RecipeForAHeist
        values:
            rpgtitle: Recipe for a Heist
            rpgdescription: Obtaining Grandmama’s Shortbread Recipe
    -
        scope:
            path: RollForShoes/RulesAndResources
        values:
            rpgtitle: Rules and Resources
            rpgdescription: Summary of Roll for Shoes micro-ttRPG
    -
        scope:
            path: Shadowrun/5e/LoneStar
        values:
            rpgtitle: Lone Star
            rpgdescription: An anti-narcotics squad
    -
        scope:
            path: Shadowrun/5e/ShadowrunUK
        values:
            rpgtitle: Shadowrun UK
            rpgdescription: An SR5e game set in the UK
    -
        scope:
            path: Shadowrun/5e/RulesAndResources
        values:
            rpgtitle: Rules and Resources
            rpgdescription: Our Summary of SR5e Rules
    -
        scope:
            path: Starfinder/2e/Playtest
        values:
            rpgtitle: Playtest
            rpgdescription: Starfinder 2e
    -
        scope:
            path: WrathAndGlory/RulesAndResources
        values:
            rpgtitle: Rules and Resources
            rpgdescription: Various Resources for Wrath & Glory
