title: Role Playing Games
description: Combined site of RPGs I help hosting website information
titles_from_headings:
    enabled: false
defaults:
    -
        values:
            layout: default
    -
        scope:
            path: 13thAge/IlmatrasLastHope
        values:
            rpgtitle: Ilmatra’s Last Hope
            rpgdescription: A 13th Age Horror Game
    -
        scope:
            path: 13thAge/RulesAndResources
        values:
            rpgtitle: Rules and Resources
            rpgdescription: Various Resources for 13th Age
    -
        scope:
            path: 13thAge/SideCampaign
        values:
            rpgtitle: Crown of Axis
            rpgdescription: A 13th Age Side Campaign
    -
        scope:
            path: BandOfBlades/TheRoadToSkydaggerKeep
        values:
            rpgtitle: The Road to Skydagger Keep
            rpgdescription: A Band of Blades Game
    -
        scope:
            path: DungeonsAndDragons/4e/ZodiacWheel
        values:
            rpgtitle: Zodiac Wheel
            rpgdescription: A D&D4e Game About a Cycle of Little Animals
    -
        scope:
            path: DungeonsAndDragons/4e/RulesAndResources
        values:
            rpgtitle: Rules and Resources
            rpgdescription: Various Resources for D&D4e
    -
        scope:
            path: DungeonsAndDragons/5e/TalesOfAvernus
        values:
            rpgtitle: Tales of Avernus
            rpgdescription: A D&D5e game about going into hell
    -
        scope:
            path: Lancer/OperationSolsticeRain
        values:
            rpgtitle: Operation Solstice Rain
            rpgdescription: A Lancer side game
    -
        scope:
            path: Lancer/WhiskeyCompany
        values:
            rpgtitle: Whiskey Company
            rpgdescription: A Lancer game following the exploits of Whiskey Company
    -
        scope:
            path: RighteousBlood/BloodAndHonour
        values:
            rpgtitle: Blood and Honour
            rpgdescription: Righteous Blood Adventures
    -
        scope:
            path: RighteousBlood/RulesAndResources
        values:
            rpgtitle: Rules and Resources
            rpgdescription: Wuxia Roleplaying Quick Reference
    -
        scope:
            path: RollForShoes/KitchenKhaos
        values:
            rpgtitle: Kitchen Khaos
            rpgdescription: Courtly servants rush to prepare and serve a fantastical feast
    -
        scope:
            path: Shadowrun/5e/LoneStar
        values:
            rpgtitle: Lone Star
            rpgdescription: An anti-narcotics squad
    -
        scope:
            path: Shadowrun/5e/ShadowrunUK
        values:
            rpgtitle: Shadowrun UK
            rpgdescription: An SR5e game set in the UK
            rpgrootlink: Shadowrun/5e/ShadowrunUK/
    -
        scope:
            path: Shadowrun/5e/ShadowrunUK/AdventureLog
        values:
            subtitlesuffix: Adventure Log
            backlink: ./
    -
        scope:
            path: Shadowrun/5e/ShadowrunUK/Contacts
        values:
            subtitlesuffix: Contacts
            backlink: ./
    -
        scope:
            path: Shadowrun/5e/RulesAndResources
        values:
            rpgtitle: "Shadowrun 5e: Rules and Resources"
            rpgdescription: Our Summary of SR5e Rules
            rpgrootlink: Shadowrun/5e/RulesAndResources/
    -
        scope:
            path: WrathAndGlory/GacromosHeresy
        values:
            rpgtitle: Gacromos Heresy
            rpgdescription: Hunt the Heretek
    -
        scope:
            path: WrathAndGlory/RulesAndResources
        values:
            rpgtitle: Rules and Resources
            rpgdescription: Various Resources for Wrath & Glory
